// API_KEY disponibile su tutte le fetch. è una chiave univoca per TUTTI del gruppo 4

export const API_KEY_BASE = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmRlYmI2OTRkMGRlZjAwMTVjZWYxMDIiLCJpYXQiOjE3MjU4NzMwMDEsImV4cCI6MTcyNzA4MjYwMX0.jen6eAIErfA8GNhPDGgw0BwoY4NoYo4kbHo2PdlyOTM';
export const API_KEY_COMMENTS = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmU0MzQ2YjgwMDY3ZDAwMTUxMjQ0ODEiLCJpYXQiOjE3MjYyMzE2NTksImV4cCI6MTcyNzQ0MTI1OX0.1-blnDAGynnj9eBxkFt-U9Chfa9ddBefbdirX5qowaA';
