// API_KEY disponibile su tutte le fetch. è una chiave univoca per TUTTI del gruppo 4

export const API_KEY_BASE = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmRlYmI2OTRkMGRlZjAwMTVjZWYxMDIiLCJpYXQiOjE3MjU4NzMwMDEsImV4cCI6MTcyNzA4MjYwMX0.jen6eAIErfA8GNhPDGgw0BwoY4NoYo4kbHo2PdlyOTM';
export const API_KEY_COMMENTS = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmM3Mjk3NTI4YWI5NjAwMTU2NjRmMDgiLCJpYXQiOjE3MjYyMTYyNzQsImV4cCI6MTcyNzQyNTg3NH0.g4aP23EdfcVizHbv-brLJRFVRAfKB37mSp1kNn9Krz0';
